-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `doctor` VALUES ('6', null, null, 'sdsa', '1322222323', '小王', '0', '2012-12-04 00:45:05', '0', '外科', 'yy', '2012-12-05 21:28:24', '4', '20', null, null, null, null, null, null, null, '未激活');
INSERT INTO `doctor` VALUES ('9', null, null, '11', '11', '殷渝', '0', '2012-12-04 16:10:04', '0', '内科', 'yy', '2012-12-04 21:45:26', '9', '20', null, null, null, null, null, null, null, '未激活');
INSERT INTO `employee` VALUES ('4', '23', '胡锦涛', '23', '0', '2', 'yy', '673918', null, '16', null, null, 'MR');
INSERT INTO `employee` VALUES ('6', '12', '1212', '23', '0', '1', 'yy', '538927', '4', '15', null, null, 'MR');
INSERT INTO `employee` VALUES ('7', '12121', '23232', '2222', '0', '2', 'yy', '984526', null, '17', null, null, 'DSM');
INSERT INTO `employee` VALUES ('9', '111', '小李', '122', '0', '4', 'yy', '471932', '4', '13', null, null, 'MARKET');
INSERT INTO `menu` VALUES ('1', null, '1', '网站首页', '001', '1', null, null);
INSERT INTO `menu` VALUES ('2', null, '1', '项目介绍', '002', '1', null, null);
INSERT INTO `menu` VALUES ('3', null, '1', '项目管理', '003', '1', null, null);
INSERT INTO `menu` VALUES ('4', null, '1', '积分兑换', '004', '1', null, null);
INSERT INTO `menu` VALUES ('5', null, '2', '兑换产品管理', '004-001', '1', null, null);
INSERT INTO `menu` VALUES ('6', null, '2', '兑换统计', '004-002', '1', null, null);
INSERT INTO `menu` VALUES ('7', null, '1', '文献资料', '005', '1', null, null);
INSERT INTO `menu` VALUES ('8', null, '2', '文献资料查看', '005-001', '1', null, null);
INSERT INTO `menu` VALUES ('9', null, '2', '文献资料管理', '005-002', '1', null, null);
INSERT INTO `menu` VALUES ('10', null, '1', '活动公告栏', '006', '1', null, null);
INSERT INTO `menu` VALUES ('11', null, '2', '活动公告管理', '006-001', '1', null, null);
INSERT INTO `menu` VALUES ('12', null, '2', '网站公告管理', '006-002', '1', null, null);
INSERT INTO `menu` VALUES ('13', null, '1', '人员管理', '007', '1', null, null);
INSERT INTO `menu` VALUES ('14', null, '2', '医师管理', '007-001', '1', null, null);
INSERT INTO `menu` VALUES ('15', null, '2', '销售代表管理', '007-002', '1', null, null);
INSERT INTO `menu` VALUES ('16', null, '2', '人员调度管理', '007-003', '1', null, null);
INSERT INTO `menu` VALUES ('17', null, '1', '题目管理', '008', '1', null, null);
INSERT INTO `menu` VALUES ('18', null, '2', '题目统计', '008-001', '1', null, null);
INSERT INTO `menu` VALUES ('19', null, '1', '权限管理', '009', '1', null, null);
INSERT INTO `menu` VALUES ('20', null, '2', '管理员账户管理', '009-001', '1', null, null);
INSERT INTO `menu` VALUES ('21', null, '2', '角色管理', '009-002', '1', null, null);
INSERT INTO `menu` VALUES ('22', null, '2', '用户角色分配', '009-003', '1', null, null);
INSERT INTO `menu` VALUES ('23', null, '1', '新建', '010', '2', null, null);
INSERT INTO `menu` VALUES ('24', null, '1', '修改', '011', '2', null, null);
INSERT INTO `menu` VALUES ('25', null, '1', '查看', '012', '2', null, null);
INSERT INTO `menu` VALUES ('26', null, '1', '删除', '012', '2', null, null);
INSERT INTO `region` VALUES ('7', null, null, '1', null, null, '0', '福建大区');
INSERT INTO `region` VALUES ('11', null, null, null, null, null, '7', '江北三区');
INSERT INTO `region` VALUES ('12', null, null, null, null, null, '7', '南坪一区');
INSERT INTO `region` VALUES ('13', '', null, '2', null, null, '7', '长江二区');
INSERT INTO `region` VALUES ('15', null, null, null, null, null, '7', '南山二区');
INSERT INTO `region` VALUES ('16', null, null, null, null, null, '7', '北部新区');
INSERT INTO `region` VALUES ('17', null, null, null, null, null, '0', '上海大区');
INSERT INTO `region` VALUES ('18', null, null, null, null, null, '17', '浦东二区');
INSERT INTO `region` VALUES ('19', null, null, null, null, null, '18', '天府小区');
INSERT INTO `region` VALUES ('20', '12', null, '3', null, null, '12', '五公里医院');
INSERT INTO `region` VALUES ('21', '1232322', null, '3', null, null, '19', '重庆长城医院');
INSERT INTO `region` VALUES ('22', null, null, null, null, null, '0', '北京大区');
INSERT INTO `region` VALUES ('23', null, null, null, null, null, '0', '山东大区');
INSERT INTO `region` VALUES ('24', '', null, '1', null, null, '0', '天河大区');
INSERT INTO `region` VALUES ('25', null, null, null, null, null, '0', '东北大区');
INSERT INTO `region` VALUES ('27', null, null, null, null, null, '0', '西北大区');
INSERT INTO `region` VALUES ('28', null, null, null, null, null, '0', '西南大区');
INSERT INTO `region` VALUES ('29', '', null, '4', null, null, '21', '重庆长城医院住院部');
INSERT INTO `region` VALUES ('30', null, null, null, null, null, '22', '北京协和医院');
INSERT INTO `region` VALUES ('31', null, null, '1', null, null, '0', '华中大区');
INSERT INTO `roleforuser` VALUES ('1', '系统管理员', '0');
INSERT INTO `roleforuser` VALUES ('5', '上海大区管理员', '0');
INSERT INTO `roleforuser` VALUES ('6', '福建大区管理员', '0');
INSERT INTO `roleforuser` VALUES ('7', '东北大区管理员', '0');
INSERT INTO `roleforuser` VALUES ('8', '浙江大区管理员', '0');
INSERT INTO `roleforuser` VALUES ('9', '北京大区管理员', '0');
INSERT INTO `roleforuser` VALUES ('10', '广海六区管理员', '0');
INSERT INTO `roleforuser` VALUES ('11', '福建四区管理员', '0');
INSERT INTO `roleforuser` VALUES ('12', '京沪市场部管理员', '0');
INSERT INTO `roleforuser` VALUES ('13', '成渝市场部管理员', '0');
INSERT INTO `roleforuserlinkmenu` VALUES ('1', '1', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('2', '2', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('3', '3', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('4', '4', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('5', '5', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('6', '6', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('7', '7', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('8', '8', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('9', '9', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('10', '10', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('11', '11', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('12', '12', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('13', '13', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('14', '14', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('15', '15', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('16', '16', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('17', '17', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('18', '18', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('19', '19', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('20', '20', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('21', '21', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('22', '22', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('23', '23', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('24', '24', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('25', '25', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('26', '26', '1');
INSERT INTO `roleforuserlinkmenu` VALUES ('136', '1', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('137', '2', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('138', '3', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('139', '4', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('140', '5', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('141', '6', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('142', '7', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('143', '8', '12');
INSERT INTO `roleforuserlinkmenu` VALUES ('144', '1', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('145', '2', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('146', '3', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('147', '4', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('148', '5', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('149', '6', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('150', '7', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('151', '8', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('152', '9', '13');
INSERT INTO `roleforuserlinkmenu` VALUES ('153', '1', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('154', '2', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('155', '3', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('156', '4', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('157', '5', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('158', '6', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('159', '7', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('160', '8', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('161', '9', '14');
INSERT INTO `roleforuserlinkmenu` VALUES ('175', '1', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('176', '2', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('177', '4', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('178', '5', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('179', '6', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('180', '7', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('181', '8', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('182', '10', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('183', '11', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('184', '12', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('185', '23', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('186', '24', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('187', '25', '5');
INSERT INTO `roleforuserlinkmenu` VALUES ('188', '1', '6');
INSERT INTO `roleforuserlinkmenu` VALUES ('189', '2', '6');
INSERT INTO `roleforuserlinkmenu` VALUES ('190', '4', '6');
INSERT INTO `roleforuserlinkmenu` VALUES ('191', '5', '6');
INSERT INTO `roleforuserlinkmenu` VALUES ('192', '6', '6');
INSERT INTO `roleforuserlinkmenu` VALUES ('193', '1', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('194', '2', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('195', '4', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('196', '5', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('197', '6', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('198', '7', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('199', '8', '7');
INSERT INTO `roleforuserlinkmenu` VALUES ('200', '1', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('201', '2', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('202', '3', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('203', '4', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('204', '5', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('205', '6', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('206', '7', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('207', '8', '8');
INSERT INTO `roleforuserlinkmenu` VALUES ('208', '1', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('209', '2', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('210', '3', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('211', '4', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('212', '5', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('213', '6', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('214', '7', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('215', '8', '9');
INSERT INTO `roleforuserlinkmenu` VALUES ('216', '1', '10');
INSERT INTO `roleforuserlinkmenu` VALUES ('217', '2', '10');
INSERT INTO `roleforuserlinkmenu` VALUES ('218', '3', '10');
INSERT INTO `roleforuserlinkmenu` VALUES ('219', '4', '10');
INSERT INTO `roleforuserlinkmenu` VALUES ('220', '5', '10');
INSERT INTO `roleforuserlinkmenu` VALUES ('221', '6', '10');
INSERT INTO `roleforuserlinkmenu` VALUES ('222', '1', '11');
INSERT INTO `roleforuserlinkmenu` VALUES ('223', '2', '11');
INSERT INTO `roleforuserlinkmenu` VALUES ('224', '3', '11');
INSERT INTO `roleforuserlinkmenu` VALUES ('225', '4', '11');
INSERT INTO `roleforuserlinkmenu` VALUES ('226', '5', '11');
INSERT INTO `roleforuserlinkmenu` VALUES ('227', '6', '11');
INSERT INTO `rolelinkuser` VALUES ('1', '1', '1');
INSERT INTO `rolelinkuser` VALUES ('2', '5', '1');
INSERT INTO `rolelinkuser` VALUES ('3', '1', '1');
INSERT INTO `rolelinkuser` VALUES ('4', '1', '1');
INSERT INTO `rolelinkuser` VALUES ('5', '1', '4');
INSERT INTO `rolelinkuser` VALUES ('6', '5', '9');
INSERT INTO `rolelinkuser` VALUES ('7', '5', '6');
